# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/simCPU/simCPU.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simCPU || ORIG_REF_NAME==simCPU} -quiet] -quiet

# IP: bd/simCPU/ip/simCPU_MCPU_0_0/simCPU_MCPU_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simCPU_MCPU_0_0 || ORIG_REF_NAME==simCPU_MCPU_0_0} -quiet] -quiet

# IP: bd/simCPU/ip/simCPU_dist_mem_gen_0_0/simCPU_dist_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simCPU_dist_mem_gen_0_0 || ORIG_REF_NAME==simCPU_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/simCPU/ip/simCPU_xlslice_0_0/simCPU_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simCPU_xlslice_0_0 || ORIG_REF_NAME==simCPU_xlslice_0_0} -quiet] -quiet

# IP: bd/simCPU/ip/simCPU_RAM_B_0_0/simCPU_RAM_B_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simCPU_RAM_B_0_0 || ORIG_REF_NAME==simCPU_RAM_B_0_0} -quiet] -quiet

# IP: c:/Users/liang/Desktop/OrgLab/lab4/simCPU/simCPU.gen/sources_1/bd/simCPU/ip/simCPU_RAM_B_0_0/RAM_B.srcs/sources_1/ip/RAM/RAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet

# IP: bd/simCPU/ip/simCPU_xlslice_0_1/simCPU_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simCPU_xlslice_0_1 || ORIG_REF_NAME==simCPU_xlslice_0_1} -quiet] -quiet

# IP: bd/simCPU/ip/simCPU_util_vector_logic_0_0/simCPU_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simCPU_util_vector_logic_0_0 || ORIG_REF_NAME==simCPU_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Users/liang/Desktop/OrgLab/lab4/simCPU/simCPU.gen/sources_1/bd/simCPU/ip/simCPU_dist_mem_gen_0_0/simCPU_dist_mem_gen_0_0_ooc.xdc

# XDC: c:/Users/liang/Desktop/OrgLab/lab4/simCPU/simCPU.gen/sources_1/bd/simCPU/ip/simCPU_RAM_B_0_0/RAM_B.srcs/sources_1/ip/RAM/RAM_ooc.xdc

# XDC: c:/Users/liang/Desktop/OrgLab/lab4/simCPU/simCPU.gen/sources_1/bd/simCPU/simCPU_ooc.xdc
