# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ALU/ALU.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU || ORIG_REF_NAME==ALU} -quiet] -quiet

# IP: bd/ALU/ip/ALU_xlslice_0_0/ALU_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_xlslice_0_0 || ORIG_REF_NAME==ALU_xlslice_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_xlslice_0_1/ALU_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_xlslice_0_1 || ORIG_REF_NAME==ALU_xlslice_0_1} -quiet] -quiet

# IP: bd/ALU/ip/ALU_SignalExt_32_0_0/ALU_SignalExt_32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_SignalExt_32_0_0 || ORIG_REF_NAME==ALU_SignalExt_32_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_xor32_0_0/ALU_xor32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_xor32_0_0 || ORIG_REF_NAME==ALU_xor32_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_xlslice_2_0/ALU_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_xlslice_2_0 || ORIG_REF_NAME==ALU_xlslice_2_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_xlconstant_0_0/ALU_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_xlconstant_0_0 || ORIG_REF_NAME==ALU_xlconstant_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_addc_32_0_0/ALU_addc_32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_addc_32_0_0 || ORIG_REF_NAME==ALU_addc_32_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_xlconcat_0_0/ALU_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_xlconcat_0_0 || ORIG_REF_NAME==ALU_xlconcat_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_or32_0_0/ALU_or32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_or32_0_0 || ORIG_REF_NAME==ALU_or32_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_xor32_1_0/ALU_xor32_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_xor32_1_0 || ORIG_REF_NAME==ALU_xor32_1_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_nor32_0_0/ALU_nor32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_nor32_0_0 || ORIG_REF_NAME==ALU_nor32_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_srl32_0_0/ALU_srl32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_srl32_0_0 || ORIG_REF_NAME==ALU_srl32_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_MUX8T1_32_0_0/ALU_MUX8T1_32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_MUX8T1_32_0_0 || ORIG_REF_NAME==ALU_MUX8T1_32_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_or_bit_32_0_0/ALU_or_bit_32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_or_bit_32_0_0 || ORIG_REF_NAME==ALU_or_bit_32_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_util_vector_logic_0_0/ALU_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ALU_util_vector_logic_0_0 || ORIG_REF_NAME==ALU_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Users/liang/Desktop/OrgLab/lab1/ALU/ALU.gen/sources_1/bd/ALU/ALU_ooc.xdc
