# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/muxctrl.xdc

# Block Designs: bd/OExp01_muxctrl/OExp01_muxctrl.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl || ORIG_REF_NAME==OExp01_muxctrl} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_MUX2T1_5_0_0/OExp01_muxctrl_MUX2T1_5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_MUX2T1_5_0_0 || ORIG_REF_NAME==OExp01_muxctrl_MUX2T1_5_0_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_MUX2T1_5_1_0/OExp01_muxctrl_MUX2T1_5_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_MUX2T1_5_1_0 || ORIG_REF_NAME==OExp01_muxctrl_MUX2T1_5_1_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_MUX4T1_5_1_0/OExp01_muxctrl_MUX4T1_5_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_MUX4T1_5_1_0 || ORIG_REF_NAME==OExp01_muxctrl_MUX4T1_5_1_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlslice_0_0/OExp01_muxctrl_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlslice_0_0 || ORIG_REF_NAME==OExp01_muxctrl_xlslice_0_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlslice_1_0/OExp01_muxctrl_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlslice_1_0 || ORIG_REF_NAME==OExp01_muxctrl_xlslice_1_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlconcat_0_0/OExp01_muxctrl_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlconcat_0_0 || ORIG_REF_NAME==OExp01_muxctrl_xlconcat_0_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlconcat_1_0/OExp01_muxctrl_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlconcat_1_0 || ORIG_REF_NAME==OExp01_muxctrl_xlconcat_1_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlconstant_0_0/OExp01_muxctrl_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlconstant_0_0 || ORIG_REF_NAME==OExp01_muxctrl_xlconstant_0_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlconstant_1_0/OExp01_muxctrl_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlconstant_1_0 || ORIG_REF_NAME==OExp01_muxctrl_xlconstant_1_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlslice_2_0/OExp01_muxctrl_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlslice_2_0 || ORIG_REF_NAME==OExp01_muxctrl_xlslice_2_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlslice_3_0/OExp01_muxctrl_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlslice_3_0 || ORIG_REF_NAME==OExp01_muxctrl_xlslice_3_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_MUX8T1_8_0_0/OExp01_muxctrl_MUX8T1_8_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_MUX8T1_8_0_0 || ORIG_REF_NAME==OExp01_muxctrl_MUX8T1_8_0_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlconstant_2_0/OExp01_muxctrl_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlconstant_2_0 || ORIG_REF_NAME==OExp01_muxctrl_xlconstant_2_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlconstant_3_0/OExp01_muxctrl_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlconstant_3_0 || ORIG_REF_NAME==OExp01_muxctrl_xlconstant_3_0} -quiet] -quiet

# XDC: bd/OExp01_muxctrl/OExp01_muxctrl_ooc.xdc
