# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/liang/Desktop/OrgLab/lab2/Org-Sword.xdc

# Block Designs: bd/CSSTE/CSSTE.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE || ORIG_REF_NAME==CSSTE} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_MIO_BUS_0_0/CSSTE_MIO_BUS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_MIO_BUS_0_0 || ORIG_REF_NAME==CSSTE_MIO_BUS_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_Multi_8CH32_0_0/CSSTE_Multi_8CH32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_Multi_8CH32_0_0 || ORIG_REF_NAME==CSSTE_Multi_8CH32_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_SPIO_0_0/CSSTE_SPIO_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_SPIO_0_0 || ORIG_REF_NAME==CSSTE_SPIO_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_SAnti_jitter_0_0/CSSTE_SAnti_jitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_SAnti_jitter_0_0 || ORIG_REF_NAME==CSSTE_SAnti_jitter_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_Counter_x_0_0/CSSTE_Counter_x_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_Counter_x_0_0 || ORIG_REF_NAME==CSSTE_Counter_x_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_SSeg7_Dev_0_0/CSSTE_SSeg7_Dev_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_SSeg7_Dev_0_0 || ORIG_REF_NAME==CSSTE_SSeg7_Dev_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_clk_div_0_0/CSSTE_clk_div_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_clk_div_0_0 || ORIG_REF_NAME==CSSTE_clk_div_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_dist_mem_gen_0_0/CSSTE_dist_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_dist_mem_gen_0_0 || ORIG_REF_NAME==CSSTE_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_div11_0/CSSTE_div11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_div11_0 || ORIG_REF_NAME==CSSTE_div11_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_div11_1/CSSTE_div11_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_div11_1 || ORIG_REF_NAME==CSSTE_div11_1} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_div20_0/CSSTE_div20_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_div20_0 || ORIG_REF_NAME==CSSTE_div20_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_div20_1/CSSTE_div20_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_div20_1 || ORIG_REF_NAME==CSSTE_div20_1} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_sw0_0/CSSTE_sw0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_sw0_0 || ORIG_REF_NAME==CSSTE_sw0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_sw2_0/CSSTE_sw2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_sw2_0 || ORIG_REF_NAME==CSSTE_sw2_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_util_vector_logic_0_0/CSSTE_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_util_vector_logic_0_0 || ORIG_REF_NAME==CSSTE_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlconcat_0_0/CSSTE_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_xlconcat_0_0 || ORIG_REF_NAME==CSSTE_xlconcat_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlconcat_0_1/CSSTE_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_xlconcat_0_1 || ORIG_REF_NAME==CSSTE_xlconcat_0_1} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlconstant_0_0/CSSTE_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_xlconstant_0_0 || ORIG_REF_NAME==CSSTE_xlconstant_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlconstant_0_1/CSSTE_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_xlconstant_0_1 || ORIG_REF_NAME==CSSTE_xlconstant_0_1} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_0/CSSTE_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_0 || ORIG_REF_NAME==CSSTE_xlslice_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_2/CSSTE_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_2 || ORIG_REF_NAME==CSSTE_xlslice_0_2} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_3/CSSTE_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_3 || ORIG_REF_NAME==CSSTE_xlslice_0_3} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_4/CSSTE_xlslice_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_4 || ORIG_REF_NAME==CSSTE_xlslice_0_4} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_5/CSSTE_xlslice_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_5 || ORIG_REF_NAME==CSSTE_xlslice_0_5} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_6/CSSTE_xlslice_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_6 || ORIG_REF_NAME==CSSTE_xlslice_0_6} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_7/CSSTE_xlslice_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_7 || ORIG_REF_NAME==CSSTE_xlslice_0_7} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_RAM_B_0_2/CSSTE_RAM_B_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_RAM_B_0_2 || ORIG_REF_NAME==CSSTE_RAM_B_0_2} -quiet] -quiet

# IP: c:/Users/liang/Desktop/OrgLab/lab4/SOC/SOC.gen/sources_1/bd/CSSTE/ip/CSSTE_RAM_B_0_2/RAM_B.srcs/sources_1/ip/RAM/RAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_8/CSSTE_xlslice_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_8 || ORIG_REF_NAME==CSSTE_xlslice_0_8} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_VGA_orig_0_0/CSSTE_VGA_orig_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_VGA_orig_0_0 || ORIG_REF_NAME==CSSTE_VGA_orig_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_SCPUC_0_0/CSSTE_SCPUC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_SCPUC_0_0 || ORIG_REF_NAME==CSSTE_SCPUC_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_1_0/CSSTE_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_1_0 || ORIG_REF_NAME==CSSTE_xlslice_1_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_util_vector_logic_1_0/CSSTE_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CSSTE_util_vector_logic_1_0 || ORIG_REF_NAME==CSSTE_util_vector_logic_1_0} -quiet] -quiet

# XDC: c:/Users/liang/Desktop/OrgLab/lab4/SOC/SOC.gen/sources_1/bd/CSSTE/ip/CSSTE_dist_mem_gen_0_0/CSSTE_dist_mem_gen_0_0_ooc.xdc

# XDC: c:/Users/liang/Desktop/OrgLab/lab4/SOC/SOC.gen/sources_1/bd/CSSTE/ip/CSSTE_RAM_B_0_2/RAM_B.srcs/sources_1/ip/RAM/RAM_ooc.xdc

# XDC: c:/Users/liang/Desktop/OrgLab/lab4/SOC/SOC.gen/sources_1/bd/CSSTE/CSSTE_ooc.xdc
